apps/quotation/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^addToList', views.addToList, name="addToList"),
    url(r'^addToMyList/(?P<id>\d*)$', views.addToMyList, name="addToMyList"),
    url(r'^viewUser/(?P<user_id>\d*)$', views.viewUser, name="viewUser"),
    url(r'^deleteList/(?P<id>\d*)$', views.deleteList, name="deleteList")
]

belt_exam2/apps/quotation/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^addToList', views.addToList, name="addToList"),
    url(r'^addToMyList/(?P<id>\d*)$', views.addToMyList, name="addToMyList"),
    url(r'^viewUser/(?P<user_id>\d*)$', views.viewUser, name="viewUser"),
    url(r'^deleteList/(?P<id>\d*)$', views.deleteList, name="deleteList")
]

belt_exam2/belt_exam2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls')),
    url(r'^quotation/', include('apps.quotation.urls', namespace="quotation")),
    url(r'^admin/', admin.site.urls),
]

belt_exam2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls')),
    url(r'^quotation/', include('apps.quotation.urls', namespace="quotation")),
    url(r'^admin/', admin.site.urls),
]

apps/quotation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from ..login.models import User
import datetime

# Create your models here.
class QuoteManager(models.Manager):
    def addQuote(self, postData):
        user = User.objects.get(id=postData['user'])
        try:
            existing_quote = Quotation.objects.get(quotation=postData['quotation'])
            error = "The same quotation already exists!"
            return error
        except:            
            return Quotation.objects.create(quotation=postData['quotation'], user=user, quoter=postData['quoter'])

    def getUnfavoritedQuotes(self, user_id):
        unfav_quotes = []
        quotes = Quotation.objects.all().order_by('-id')
        for quote in quotes:
            if len(quote.favorited_by.filter(id=user_id)) == 0:
                unfav_quotes.append(quote)
        return unfav_quotes

    def getQuote(self, user_id):
        return Quotation.objects.filter(user=User.objects.get(id=user_id))

    def getAllQuote(self):
        return Quotation.objects.all()

    def getAllFav(self, user_id):        
        return Quotation.objects.filter(favorited_by=User.objects.get(id=user_id))    
    # return User.objects.get(id=user_id).favorites.all()
    
    def validateQuote(self, postData):
        errorMessages = []
        if len(postData['quoter']) < 3:
            errorMessages.append('Quoter has to be more than 3 characters')
        if len(postData['quotation']) < 10:
            errorMessages.append('Message has to be more than 10 characters')
        return errorMessages

    def addFav(self, user_id, quote_id):
        this_user = User.objects.get(id=user_id)
        this_quote = Quotation.objects.get(id=quote_id)
        errors = []

        if len(User.objects.filter(id=user_id)) == 0:
            errors.append('This is not a user')
        try:
            existing_quote = Quotation.objects.get(user=this_user)
            error = "The same favorite quotation already exists!"
            return error
        except:
            return this_user.favorites.add(this_quote)
    
    def deleteFav(self, user_id, quote_id):
        this_user = User.objects.get(id=user_id)
        this_quote = this_user.favorites.all().get(id=quote_id)
        errors = []

        if len(User.objects.filter(id=user_id)) == 0:
            errors.append('This is not a user')
        try:
            existing_quote = Quotation.objects.get(user=this_user)
            error = "The same favorite quotation already exists!"
            return error
        except:
            return this_user.favorites.remove(this_quote)



        # this_user = User.objects.get(id=user_id)
        # this_quote = this_user.favorites.all().get(id=quote_id)
        # # this_quote = this_user.favorites.get(id=quote_id)
        # # errors = []
        # # if len(User.objects.filter(id=user_id)) == 0:
        # #     errors.append('This is not a user')
        # # try:
        # #     existing_quote = Quotation.objects.get(user=this_user)
        # #     error = "The same favorite quotation already exists!"
        # #     return error
        # # except:
        # #     print 'in the except'
        # return this_user.favorites.remove(this_quote)

class Quotation(models.Model):
    quotation = models.CharField(max_length=255)
    quoter = models.CharField(max_length=55)
    user = models.ForeignKey(User, related_name="uploaded_quote")
    favorited_by = models.ManyToManyField(User, related_name="favorites")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuoteManager()

belt_exam2/apps/quotation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from ..login.models import User
import datetime

# Create your models here.
class QuoteManager(models.Manager):
    # def sortByCreatedAt(self):
    #     return 
    def addQuote(self, postData):
        user = User.objects.get(id=postData['user'])
        try:
            existing_quote = Quotation.objects.get(quotation=postData['quotation'])
            error = "The same quotation already exists!"
            return error
        except:            
            return Quotation.objects.create(quotation=postData['quotation'], user=user, quoter=postData['quoter'])

    def getQuote(self, user_id):
        return Quotation.objects.filter(user=User.objects.get(id=user_id))

    def getAllQuote(self):
        return Quotation.objects.all()
    # def getAllFav(self, id):
    #     q = Quotation.objects.get(id=id)
    #     return q.favorited_by.all()

class FavoriteManager(models.Manager):
    def getAllFav(self):
        return Favorite.objects.all()

    def getFav(self, user_id):
        return Favorite.objects.filter(user=User.objects.get(id=user_id))

    def addFav(self, postData):
        quote = Quotation.objects.get(id=postData['quote_id'])
        user = User.objects.get(id=postData['user'])
        try:
            existing_quote = Quotation.objects.get(quotation=postData['quotation'])
            error = "The same favorite quotation already exists!"
            return error
        except:            
            return Favorite.objects.create(favorites=quote, quotation=postData['quotation'], quoter=postData['quoter'], user=user)

class ValidateManager(models.Manager):
    def quote(self, postData):
        errorMessages = []
        if len(postData['quoter'] < 3):
            errorMessages.append('Quoter has to be more than 3 characters')
        if len(postData['message'] < 10):
            errorMessages.append('Message has to be more than 10 characters')
        return errorMessages
        

class Quotation(models.Model):
    quotation = models.CharField(max_length=255)
    quoter = models.CharField(max_length=55)
    user = models.ForeignKey(User, related_name="uploaded_quote")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuoteManager()

class Favorite(models.Model):
    quotation = models.CharField(max_length=255)
    quoter = models.CharField(max_length=55)
    favorites = models.ManyToManyField(User, related_name="favorited_by")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = FavoriteManager()

apps/quotation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import User, Quotation
from django.contrib import messages
import datetime

# Create your views here.
def index(request):
    if 'user_id' not in request.session:
        return redirect('/')
    else:        
        context = { 'quotes': Quotation.objects.getUnfavoritedQuotes(request.session['user_id']),
                    'user': User.objects.get(id=request.session['user_id']),
                    'favs': Quotation.objects.getAllFav(request.session['user_id']) }
        return render(request,'quotation/index.html', context)

def addToList(request):
    if request.method == "POST":
        quote = Quotation.objects.validateQuote(request.POST)     
        if quote:
            for error in quote:
                messages.add_message(request, messages.INFO, error)
            return redirect('/quotation')
        else:
            postData = { 'user': request.session['user_id'],
                        'quotation': request.POST['quotation'],
                        'quoter': request.POST['quoter'] }
            quotation = Quotation.objects.addQuote(postData)
            if not isinstance(quotation, Quotation):
                messages.add_message(request, messages.ERROR, quotation)        
                return redirect('quotation/addToList') 
            return redirect('/quotation')

def addToMyList(request, id):        
    try:
        if request.method == "POST":            
            # add to favorite
            Quotation.objects.addFav(request.session['user_id'], id)
            return redirect('/quotation')
    except:
        print 'Cannot add to list'
        return redirect('/quotation')

def deleteList(request, id):
    try:
        if request.method == "POST":
            Quotation.objects.deleteFav(request.session['user_id'], id)
            return redirect('/quotation')
    except:
        print 'Cannot remove from fav list'
        return redirect('/quotation')   

def viewUser(request, user_id):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        context = { 'user': User.objects.get(id=user_id),
                    'quotes': Quotation.objects.getQuote(user_id),
                    'count': Quotation.objects.getQuote(user_id).count() }
        return render(request, 'quotation/user.html', context)

belt_exam2/apps/quotation/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import User, Quotation, Favorite
from django.contrib import messages
import datetime

# Create your views here.
def index(request):
            # 'quotes' : Quotation.objects.getQuote(request.session['user_id']
    context = { 'quotes': Quotation.objects.getAllQuote(),
                'user': User.objects.get(id=request.session['user_id']),
                'favs': Favorite.objects.getAllFav() }
    return render(request,'quotation/index.html', context)

def addToList(request):
    if request.method == "POST":
        postData = { 'user': request.session['user_id'],
                     'quotation': request.POST['quotation'],
                     'quoter': request.POST['quoter'] }
        quotation = Quotation.objects.addQuote(postData)
        quote = Quotation.objects.quote(request.POST)
        if isinstance(quote, list):
            for error in quote:
                messages.add_message(request, messages.INFO, error)
        if not isinstance(quotation, Quotation):
            messages.add_message(request, messages.ERROR, quotation)        
            return redirect('quotation/addToList') 
        return redirect('/quotation')
    elif request.method == "GET":        
        context = { 'quotation': Quotation.objects.all() } 
        return render(request, 'quotation/add.html', context)   

def addToMyList(request, id):    
    try:
        if request.method == "GET":
            context = { 'quotation': Quotation.objects.get(id=id) }            
        elif request.method == "POST":
            context = { 'quotation': Quotation.objects.get(id=id) }
            # add to favorite before deleting
            postData = { 'user': request.session['user_id'],
                        'quote_id' : id,
                        'quotation': context['quotation'].quotation,
                        'quoter': context['quotation'].quoter }
            Favorite.objects.addFav(postData)
            # delete from Quotation
            Quotation.objects.get(id=id).delete()
            return redirect('/quotation', context)
    except:
        print 'Cannot delete this list'



def deleteList(request, id):
    try:
        if request.method == "GET":
            context = { 'favorite': Favorite.objects.get(id=id) }
            if request.session['user_id'] != context['favorite'].user.id:
                print 'Cannot delete this list'
            else:
                return render(request, 'quotation/delete.html', context)
        elif request.method == "POST":
            context = { 'favorite': Favorite.objects.get(id=id) }
            # add to quotation before deleting
            postData = { 'user': context['favorite'].user,
                         'quotation': context['favorite'].quotation,
                         'quoter': context['favorite'].quoter }
            Quotation.objects.addQuote(postData)
            # delete from Favorite
            Favorite.objects.get(id=id).delete()

            return redirect('/quotation', context)
    except:
        print 'Cannot delete this list'


    return redirect('/quotation')

def viewUser(request, user_id):
    context = { 'user': User.objects.get(id=user_id),
                'quotes': Quotation.objects.getQuote(user_id),
                'count': Quotation.objects.getQuote(user_id).count() }
    return render(request, 'quotation/user.html', context)

belt_exam2/apps/quotation/templates/quotation/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
    <h4>Are you sure you want to delete your review for {{review.book.title}}?</h4>
    <p>Review:</p>
    <p>{{review.review}}</p>
    <form action="{% url 'books:deleteReview' id=review.id %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Confirm">
        <button type="button" class="btn btn-default"><a href="{% url 'books:index' %}" id="hrefbtn">Cancel</a></button>
    </form>
</body>
</html>

belt_exam2/apps/quotation/templates/quotation/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quotes</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'quotation/index.css' %}">
</head>
<body>
    <div class="wrapper">
        <div id="header">
            <h1>Welcome, {{ user.first_name }}</h1>
            <a href="/logout">Logout</a>
        </div>
        
        <div id="left">
            <h3>Quotable Quotes</h3>
            {% for quote in quotes %}
                <div class="q_quotes">
                    <p>{{ quote.quoter }}: {{ quote.quotation }}</p>
                    <p id="small">Posted by <a href="/quotation/viewUser/{{ quote.user.id }}">{{ quote.user }}</a></p>
                    <form action="{% url 'quotation:addToMyList' id=quote.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Add to My List">
                    </form>
                </div>
            {% endfor %}
        </div>


        <div id="right">
            <h3>Your Favorites</h3>
            {% for fav in favs %}
                <div class="f_quotes">
                    <p>{{ fav.quoter }}: {{ fav.quotation }}</p>
                    <p id="small">Posted by <a href="/quotation/viewUser/{{ quote.user.id }}">{{ quote.user }}</a></p>
                    <form action="{% url 'quotation:deleteList' id=favs.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Remove From My List">
                    </form>
                </div>
            {% endfor %}
        </div>

        <div id="bottom">
            {% if messages %}
                {% for message in messages %}
                    <p class="error">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <h2>Contribute a Quote:</h2>
            <form action="/quotation/addToList/{{ id }}" method=post>     
                {% csrf_token %}           
                <label for="quoter">Quoted By:</label><input type="text" name="quoter" id="quoter">
                <br>
                <label for="quotation">Message:</label><textarea name="quotation" id="quotation" cols="30" rows="10"></textarea>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</html>

belt_exam2/apps/quotation/templates/quotation/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'quotation/user.css' %}">
</head>
<body>
    <div class="wrapper">    
        <div class="head">
            <a href="/quotation">Dashboard</a> | <a href="/logout">Logout</a>
        </div>

        <div>
            <p>Posts by {{ user.first_name }}</p>
            <p>Count: {{ count }}</p>
        </div>

        <div class="main-content">
            {% for quote in quotes %}
                <p><span class='red'>{{ quote.quoter }}:</span> {{ quote.quotation }}</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>